# Generated by Django 5.1 on 2024-08-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
