# Generated by Django 5.1 on 2024-09-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('intoduction', models.TextField(blank=True, null=True)),
                ('resume', models.TextField()),
                ('temps', models.TimeField()),
                ('choix_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classe')),
                ('choix_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.matiere')),
            ],
        ),
    ]
