# Generated by Django 5.1 on 2024-09-01 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='temps',
        ),
        migrations.AddField(
            model_name='cours',
            name='Date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cours',
            name='Date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
