# Generated by Django 5.1 on 2024-09-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cours_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom_matiere',
            field=models.CharField(max_length=128),
        ),
    ]
