# Generated by Django 5.1 on 2024-09-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cours_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='slug',
        ),
    ]
