# Generated by Django 5.1 on 2024-09-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_cours_slug_remove_matiere_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
