# Generated by Django 5.1 on 2024-09-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cours_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='profil_cours',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
