# Generated by Django 5.1 on 2024-09-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cours_profil_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
