# Generated by Django 5.1 on 2024-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_cours_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='slug',
        ),
        migrations.AddField(
            model_name='cours',
            name='temps_etudes',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
