# Generated by Django 5.1 on 2024-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_cours_slug_cours_temps_etudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
