# Generated by Django 5.1 on 2024-10-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_archives', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
