# Generated by Django 5.1 on 2024-10-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_archives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archives',
            old_name='nom_archives',
            new_name='nom_archive',
        ),
        migrations.AlterField(
            model_name='archives',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
