# Generated by Django 5.1 on 2024-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_prof_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_eleve', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='professeur',
            name='mat_prof',
            field=models.CharField(max_length=9),
        ),
    ]
